// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService2.proto

package grpcExampleBaeldung.src;

public final class HelloService2OuterClass {
  private HelloService2OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcExampleBaeldung_src_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcExampleBaeldung_src_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcExampleBaeldung_src_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcExampleBaeldung_src_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023HelloService2.proto\022\027grpcExampleBaeldu" +
      "ng.src\"3\n\014HelloRequest\022\021\n\tfirstName\030\001 \001(" +
      "\t\022\020\n\010lastName\030\002 \001(\t\"!\n\rHelloResponse\022\020\n\010" +
      "greeting\030\001 \001(\t2g\n\rHelloService2\022V\n\005hello" +
      "\022%.grpcExampleBaeldung.src.HelloRequest\032" +
      "&.grpcExampleBaeldung.src.HelloResponseB" +
      "\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpcExampleBaeldung_src_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpcExampleBaeldung_src_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcExampleBaeldung_src_HelloRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_grpcExampleBaeldung_src_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpcExampleBaeldung_src_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcExampleBaeldung_src_HelloResponse_descriptor,
        new java.lang.String[] { "Greeting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
